on: [push]

jobs:
  build:
    runs-on: act-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor}}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - uses: actions/checkout@v5
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ vars.REGISTRY }}/${{ github.repository }}:latest
          context: .
