on:
  push:
    tags:
      - '*'
jobs:
  forgejo:
    runs-on: act-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor}}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}
  dockerhub:
    runs-on: act-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}
