name: test-build
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'image/**'
      - 'internal/**'
      - 'static/**'
      - 'templates/**'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - 'dailimage.go'
      - 'go_build.sh'

env:
  VERSION: ${{ github.ref_name }}
  PLATFORMS: linux,darwin
  ARCHS: amd64,arm64

jobs:
  build:
    runs-on: act-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.25.0'
      - name: Build Go app
        run: bash go_build.sh
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Forgejo
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor}}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}
          file: ./Dockerfile
